name: Build and push ogmios

on:
  workflow_call:
    inputs:
      REPOSITORY:
        description: ECR repository name
        type: string
        required: true

    secrets:
      DOCKERHUB_USERNAME:
        description: Dockerhub username
        required: true
      DOCKERHUB_TOKEN:
        description: Dockerhub username
        required: true

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            dcspark/${{ inputs.REPOSITORY }}:${{ env.IMAGE_TAG }}
